wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.18
    code_path: code/usecases/wav2letter.py
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
    t:
      1:
      - 3
      - 5
      2:
      - 3
      - 5
      3:
      - 3
      4: 3.7.6
      5: 0.10.18
